version: '3.7'

services:
  apache:
    build: ./docker/images/php-apache
    image: custom-php:7.3-apache
    volumes:
      - './docker/configs/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf:rw'
      - './:/var/www:rw'
    ports:
      - "0.0.0.0::8001:80"
    depends_on:
      - db
  db:
    image: mysql:8
    volumes:
      - "./db/mysql:/var/lib/mysql:rw"
      - "./docker/configs/mysql/my.cnf:/etc/mysql/my.cnf:rw"
    environment:
      - MYSQL_ROOT_PASSWORD=123
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - '0.0.0.0:8002:80'
    depends_on:
      - db